# Generated by Django 5.1.6 on 2025-02-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fatwa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('source', models.CharField(max_length=100)),
                ('language', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], max_length=2)),
            ],
        ),
    ]
